//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://underlying.rfq.ws.leon.com/", ConfigurationName="UnderlyingMaintenanceService.UnderlyingController")]
    public interface UnderlyingController {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse getAll(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetAll(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse EndgetAll(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse updateValidity(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginupdateValidity(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse EndupdateValidity(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse save(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginsave(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse Endsave(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://underlying.rfq.ws.leon.com/")]
    public partial class underlyingDetailImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private bool isValidField;
        
        private string ricField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ric {
            get {
                return this.ricField;
            }
            set {
                this.ricField = value;
                this.RaisePropertyChanged("ric");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAll {
        
        public getAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public underlyingDetailImpl[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(underlyingDetailImpl[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidity", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidity {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isValid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updatedBy;
        
        public updateValidity() {
        }
        
        public updateValidity(string RIC, bool isValid, string updatedBy) {
            this.RIC = RIC;
            this.isValid = isValid;
            this.updatedBy = updatedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidityResponse", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateValidityResponse() {
        }
        
        public updateValidityResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RIC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string savedBy;
        
        public save() {
        }
        
        public save(string RIC, string description, string savedBy) {
            this.RIC = RIC;
            this.description = description;
            this.savedBy = savedBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://underlying.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://underlying.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveResponse() {
        }
        
        public saveResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UnderlyingControllerChannel : RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public underlyingDetailImpl[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((underlyingDetailImpl[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateValidityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateValidityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnderlyingControllerClient : System.ServiceModel.ClientBase<RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController>, RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController {
        
        private BeginOperationDelegate onBegingetAllDelegate;
        
        private EndOperationDelegate onEndgetAllDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateValidityDelegate;
        
        private EndOperationDelegate onEndupdateValidityDelegate;
        
        private System.Threading.SendOrPostCallback onupdateValidityCompletedDelegate;
        
        private BeginOperationDelegate onBeginsaveDelegate;
        
        private EndOperationDelegate onEndsaveDelegate;
        
        private System.Threading.SendOrPostCallback onsaveCompletedDelegate;
        
        public UnderlyingControllerClient() {
        }
        
        public UnderlyingControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnderlyingControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnderlyingControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnderlyingControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getAllCompletedEventArgs> getAllCompleted;
        
        public event System.EventHandler<updateValidityCompletedEventArgs> updateValidityCompleted;
        
        public event System.EventHandler<saveCompletedEventArgs> saveCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.getAll(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll request) {
            return base.Channel.getAll(request);
        }
        
        public underlyingDetailImpl[] getAll() {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll();
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.BegingetAll(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAll(System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAll();
            return ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).BegingetAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.EndgetAll(System.IAsyncResult result) {
            return base.Channel.EndgetAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public underlyingDetailImpl[] EndgetAll(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).EndgetAll(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetAll(callback, asyncState);
        }
        
        private object[] OnEndgetAll(System.IAsyncResult result) {
            underlyingDetailImpl[] retVal = this.EndgetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllCompleted(object state) {
            if ((this.getAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllCompleted(this, new getAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllAsync() {
            this.getAllAsync(null);
        }
        
        public void getAllAsync(object userState) {
            if ((this.onBegingetAllDelegate == null)) {
                this.onBegingetAllDelegate = new BeginOperationDelegate(this.OnBegingetAll);
            }
            if ((this.onEndgetAllDelegate == null)) {
                this.onEndgetAllDelegate = new EndOperationDelegate(this.OnEndgetAll);
            }
            if ((this.ongetAllCompletedDelegate == null)) {
                this.ongetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllCompleted);
            }
            base.InvokeAsync(this.onBegingetAllDelegate, null, this.onEndgetAllDelegate, this.ongetAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.updateValidity(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity request) {
            return base.Channel.updateValidity(request);
        }
        
        public bool updateValidity(string RIC, bool isValid, string updatedBy) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity();
            inValue.RIC = RIC;
            inValue.isValid = isValid;
            inValue.updatedBy = updatedBy;
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).updateValidity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.BeginupdateValidity(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateValidity(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateValidity(string RIC, bool isValid, string updatedBy, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidity();
            inValue.RIC = RIC;
            inValue.isValid = isValid;
            inValue.updatedBy = updatedBy;
            return ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).BeginupdateValidity(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.EndupdateValidity(System.IAsyncResult result) {
            return base.Channel.EndupdateValidity(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndupdateValidity(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).EndupdateValidity(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginupdateValidity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RIC = ((string)(inValues[0]));
            bool isValid = ((bool)(inValues[1]));
            string updatedBy = ((string)(inValues[2]));
            return this.BeginupdateValidity(RIC, isValid, updatedBy, callback, asyncState);
        }
        
        private object[] OnEndupdateValidity(System.IAsyncResult result) {
            bool retVal = this.EndupdateValidity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateValidityCompleted(object state) {
            if ((this.updateValidityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateValidityCompleted(this, new updateValidityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateValidityAsync(string RIC, bool isValid, string updatedBy) {
            this.updateValidityAsync(RIC, isValid, updatedBy, null);
        }
        
        public void updateValidityAsync(string RIC, bool isValid, string updatedBy, object userState) {
            if ((this.onBeginupdateValidityDelegate == null)) {
                this.onBeginupdateValidityDelegate = new BeginOperationDelegate(this.OnBeginupdateValidity);
            }
            if ((this.onEndupdateValidityDelegate == null)) {
                this.onEndupdateValidityDelegate = new EndOperationDelegate(this.OnEndupdateValidity);
            }
            if ((this.onupdateValidityCompletedDelegate == null)) {
                this.onupdateValidityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateValidityCompleted);
            }
            base.InvokeAsync(this.onBeginupdateValidityDelegate, new object[] {
                        RIC,
                        isValid,
                        updatedBy}, this.onEndupdateValidityDelegate, this.onupdateValidityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.save(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save request) {
            return base.Channel.save(request);
        }
        
        public bool save(string RIC, string description, string savedBy) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save();
            inValue.RIC = RIC;
            inValue.description = description;
            inValue.savedBy = savedBy;
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.Beginsave(RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsave(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsave(string RIC, string description, string savedBy, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.save();
            inValue.RIC = RIC;
            inValue.description = description;
            inValue.savedBy = savedBy;
            return ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).Beginsave(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController.Endsave(System.IAsyncResult result) {
            return base.Channel.Endsave(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endsave(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.UnderlyingMaintenanceService.UnderlyingController)(this)).Endsave(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string RIC = ((string)(inValues[0]));
            string description = ((string)(inValues[1]));
            string savedBy = ((string)(inValues[2]));
            return this.Beginsave(RIC, description, savedBy, callback, asyncState);
        }
        
        private object[] OnEndsave(System.IAsyncResult result) {
            bool retVal = this.Endsave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsaveCompleted(object state) {
            if ((this.saveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.saveCompleted(this, new saveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void saveAsync(string RIC, string description, string savedBy) {
            this.saveAsync(RIC, description, savedBy, null);
        }
        
        public void saveAsync(string RIC, string description, string savedBy, object userState) {
            if ((this.onBeginsaveDelegate == null)) {
                this.onBeginsaveDelegate = new BeginOperationDelegate(this.OnBeginsave);
            }
            if ((this.onEndsaveDelegate == null)) {
                this.onEndsaveDelegate = new EndOperationDelegate(this.OnEndsave);
            }
            if ((this.onsaveCompletedDelegate == null)) {
                this.onsaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsaveCompleted);
            }
            base.InvokeAsync(this.onBeginsaveDelegate, new object[] {
                        RIC,
                        description,
                        savedBy}, this.onEndsaveDelegate, this.onsaveCompletedDelegate, userState);
        }
    }
}
