//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForQuoteServicesModuleLibrary.GroupMaintenanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://group.rfq.ws.leon.com/", ConfigurationName="GroupMaintenanceService.GroupController")]
    public interface GroupController {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse updateValidity(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginupdateValidity(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse EndupdateValidity(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse save(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginsave(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse Endsave(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse delete(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Begindelete(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse Enddelete(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse getAll(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetAll(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse EndgetAll(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidity", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidity {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int groupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isValid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updatedByUser;
        
        public updateValidity() {
        }
        
        public updateValidity(int groupId, bool isValid, string updatedByUser) {
            this.groupId = groupId;
            this.isValid = isValid;
            this.updatedByUser = updatedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidityResponse", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateValidityResponse() {
        }
        
        public updateValidityResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string savedByUser;
        
        public save() {
        }
        
        public save(string groupName, string savedByUser) {
            this.groupName = groupName;
            this.savedByUser = savedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveResponse() {
        }
        
        public saveResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int groupId;
        
        public delete() {
        }
        
        public delete(int groupId) {
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://group.rfq.ws.leon.com/")]
    public partial class groupDetailImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int groupIdField;
        
        private string groupNameField;
        
        private bool isValidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAll {
        
        public getAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://group.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://group.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public groupDetailImpl[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(groupDetailImpl[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupControllerChannel : RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateValidityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateValidityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public groupDetailImpl[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((groupDetailImpl[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupControllerClient : System.ServiceModel.ClientBase<RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController>, RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController {
        
        private BeginOperationDelegate onBeginupdateValidityDelegate;
        
        private EndOperationDelegate onEndupdateValidityDelegate;
        
        private System.Threading.SendOrPostCallback onupdateValidityCompletedDelegate;
        
        private BeginOperationDelegate onBeginsaveDelegate;
        
        private EndOperationDelegate onEndsaveDelegate;
        
        private System.Threading.SendOrPostCallback onsaveCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteDelegate;
        
        private EndOperationDelegate onEnddeleteDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllDelegate;
        
        private EndOperationDelegate onEndgetAllDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllCompletedDelegate;
        
        public GroupControllerClient() {
        }
        
        public GroupControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<updateValidityCompletedEventArgs> updateValidityCompleted;
        
        public event System.EventHandler<saveCompletedEventArgs> saveCompleted;
        
        public event System.EventHandler<deleteCompletedEventArgs> deleteCompleted;
        
        public event System.EventHandler<getAllCompletedEventArgs> getAllCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.updateValidity(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity request) {
            return base.Channel.updateValidity(request);
        }
        
        public bool updateValidity(int groupId, bool isValid, string updatedByUser) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity();
            inValue.groupId = groupId;
            inValue.isValid = isValid;
            inValue.updatedByUser = updatedByUser;
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).updateValidity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.BeginupdateValidity(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateValidity(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateValidity(int groupId, bool isValid, string updatedByUser, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidity();
            inValue.groupId = groupId;
            inValue.isValid = isValid;
            inValue.updatedByUser = updatedByUser;
            return ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).BeginupdateValidity(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.EndupdateValidity(System.IAsyncResult result) {
            return base.Channel.EndupdateValidity(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndupdateValidity(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).EndupdateValidity(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginupdateValidity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int groupId = ((int)(inValues[0]));
            bool isValid = ((bool)(inValues[1]));
            string updatedByUser = ((string)(inValues[2]));
            return this.BeginupdateValidity(groupId, isValid, updatedByUser, callback, asyncState);
        }
        
        private object[] OnEndupdateValidity(System.IAsyncResult result) {
            bool retVal = this.EndupdateValidity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateValidityCompleted(object state) {
            if ((this.updateValidityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateValidityCompleted(this, new updateValidityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateValidityAsync(int groupId, bool isValid, string updatedByUser) {
            this.updateValidityAsync(groupId, isValid, updatedByUser, null);
        }
        
        public void updateValidityAsync(int groupId, bool isValid, string updatedByUser, object userState) {
            if ((this.onBeginupdateValidityDelegate == null)) {
                this.onBeginupdateValidityDelegate = new BeginOperationDelegate(this.OnBeginupdateValidity);
            }
            if ((this.onEndupdateValidityDelegate == null)) {
                this.onEndupdateValidityDelegate = new EndOperationDelegate(this.OnEndupdateValidity);
            }
            if ((this.onupdateValidityCompletedDelegate == null)) {
                this.onupdateValidityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateValidityCompleted);
            }
            base.InvokeAsync(this.onBeginupdateValidityDelegate, new object[] {
                        groupId,
                        isValid,
                        updatedByUser}, this.onEndupdateValidityDelegate, this.onupdateValidityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.save(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save request) {
            return base.Channel.save(request);
        }
        
        public bool save(string groupName, string savedByUser) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save();
            inValue.groupName = groupName;
            inValue.savedByUser = savedByUser;
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.Beginsave(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsave(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsave(string groupName, string savedByUser, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.save();
            inValue.groupName = groupName;
            inValue.savedByUser = savedByUser;
            return ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).Beginsave(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.Endsave(System.IAsyncResult result) {
            return base.Channel.Endsave(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endsave(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).Endsave(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string groupName = ((string)(inValues[0]));
            string savedByUser = ((string)(inValues[1]));
            return this.Beginsave(groupName, savedByUser, callback, asyncState);
        }
        
        private object[] OnEndsave(System.IAsyncResult result) {
            bool retVal = this.Endsave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsaveCompleted(object state) {
            if ((this.saveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.saveCompleted(this, new saveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void saveAsync(string groupName, string savedByUser) {
            this.saveAsync(groupName, savedByUser, null);
        }
        
        public void saveAsync(string groupName, string savedByUser, object userState) {
            if ((this.onBeginsaveDelegate == null)) {
                this.onBeginsaveDelegate = new BeginOperationDelegate(this.OnBeginsave);
            }
            if ((this.onEndsaveDelegate == null)) {
                this.onEndsaveDelegate = new EndOperationDelegate(this.OnEndsave);
            }
            if ((this.onsaveCompletedDelegate == null)) {
                this.onsaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsaveCompleted);
            }
            base.InvokeAsync(this.onBeginsaveDelegate, new object[] {
                        groupName,
                        savedByUser}, this.onEndsaveDelegate, this.onsaveCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.delete(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(int groupId) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete();
            inValue.groupId = groupId;
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.Begindelete(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindelete(int groupId, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.delete();
            inValue.groupId = groupId;
            return ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).Begindelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.Enddelete(System.IAsyncResult result) {
            return base.Channel.Enddelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Enddelete(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).Enddelete(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegindelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int groupId = ((int)(inValues[0]));
            return this.Begindelete(groupId, callback, asyncState);
        }
        
        private object[] OnEnddelete(System.IAsyncResult result) {
            bool retVal = this.Enddelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteCompleted(object state) {
            if ((this.deleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteCompleted(this, new deleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteAsync(int groupId) {
            this.deleteAsync(groupId, null);
        }
        
        public void deleteAsync(int groupId, object userState) {
            if ((this.onBegindeleteDelegate == null)) {
                this.onBegindeleteDelegate = new BeginOperationDelegate(this.OnBegindelete);
            }
            if ((this.onEnddeleteDelegate == null)) {
                this.onEnddeleteDelegate = new EndOperationDelegate(this.OnEnddelete);
            }
            if ((this.ondeleteCompletedDelegate == null)) {
                this.ondeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteCompleted);
            }
            base.InvokeAsync(this.onBegindeleteDelegate, new object[] {
                        groupId}, this.onEnddeleteDelegate, this.ondeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.getAll(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll request) {
            return base.Channel.getAll(request);
        }
        
        public groupDetailImpl[] getAll() {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll();
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.BegingetAll(RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAll(System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAll();
            return ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).BegingetAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController.EndgetAll(System.IAsyncResult result) {
            return base.Channel.EndgetAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public groupDetailImpl[] EndgetAll(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.GroupMaintenanceService.GroupController)(this)).EndgetAll(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetAll(callback, asyncState);
        }
        
        private object[] OnEndgetAll(System.IAsyncResult result) {
            groupDetailImpl[] retVal = this.EndgetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllCompleted(object state) {
            if ((this.getAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllCompleted(this, new getAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllAsync() {
            this.getAllAsync(null);
        }
        
        public void getAllAsync(object userState) {
            if ((this.onBegingetAllDelegate == null)) {
                this.onBegingetAllDelegate = new BeginOperationDelegate(this.OnBegingetAll);
            }
            if ((this.onEndgetAllDelegate == null)) {
                this.onEndgetAllDelegate = new EndOperationDelegate(this.OnEndgetAll);
            }
            if ((this.ongetAllCompletedDelegate == null)) {
                this.ongetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllCompleted);
            }
            base.InvokeAsync(this.onBegingetAllDelegate, null, this.onEndgetAllDelegate, this.ongetAllCompletedDelegate, userState);
        }
    }
}
