//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://holiday.rfq.ws.leon.com/", ConfigurationName="HolidayMaintenanceService.HolidayController")]
    public interface HolidayController {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse save(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginsave(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse Endsave(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse getAll(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetAll(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse EndgetAll(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse delete(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Begindelete(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse Enddelete(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse get(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginget(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse Endget(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime holidayDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addedByUser;
        
        public save() {
        }
        
        public save(string location, System.DateTime holidayDate, string addedByUser) {
            this.location = location;
            this.holidayDate = holidayDate;
            this.addedByUser = addedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveResponse() {
        }
        
        public saveResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://holiday.rfq.ws.leon.com/")]
    public partial class holidayImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime holidayDateField;
        
        private bool holidayDateFieldSpecified;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime holidayDate {
            get {
                return this.holidayDateField;
            }
            set {
                this.holidayDateField = value;
                this.RaisePropertyChanged("holidayDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool holidayDateSpecified {
            get {
                return this.holidayDateFieldSpecified;
            }
            set {
                this.holidayDateFieldSpecified = value;
                this.RaisePropertyChanged("holidayDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAll {
        
        public getAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public holidayImpl[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(holidayImpl[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime holidayDate;
        
        public delete() {
        }
        
        public delete(string location, System.DateTime holidayDate) {
            this.location = location;
            this.holidayDate = holidayDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class get {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string location;
        
        public get() {
        }
        
        public get(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://holiday.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://holiday.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public holidayImpl[] @return;
        
        public getResponse() {
        }
        
        public getResponse(holidayImpl[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HolidayControllerChannel : RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public holidayImpl[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((holidayImpl[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public holidayImpl[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((holidayImpl[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HolidayControllerClient : System.ServiceModel.ClientBase<RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController>, RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController {
        
        private BeginOperationDelegate onBeginsaveDelegate;
        
        private EndOperationDelegate onEndsaveDelegate;
        
        private System.Threading.SendOrPostCallback onsaveCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllDelegate;
        
        private EndOperationDelegate onEndgetAllDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteDelegate;
        
        private EndOperationDelegate onEnddeleteDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDelegate;
        
        private EndOperationDelegate onEndgetDelegate;
        
        private System.Threading.SendOrPostCallback ongetCompletedDelegate;
        
        public HolidayControllerClient() {
        }
        
        public HolidayControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HolidayControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HolidayControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<saveCompletedEventArgs> saveCompleted;
        
        public event System.EventHandler<getAllCompletedEventArgs> getAllCompleted;
        
        public event System.EventHandler<deleteCompletedEventArgs> deleteCompleted;
        
        public event System.EventHandler<getCompletedEventArgs> getCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.save(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save request) {
            return base.Channel.save(request);
        }
        
        public bool save(string location, System.DateTime holidayDate, string addedByUser) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save();
            inValue.location = location;
            inValue.holidayDate = holidayDate;
            inValue.addedByUser = addedByUser;
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Beginsave(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsave(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsave(string location, System.DateTime holidayDate, string addedByUser, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.save();
            inValue.location = location;
            inValue.holidayDate = holidayDate;
            inValue.addedByUser = addedByUser;
            return ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Beginsave(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Endsave(System.IAsyncResult result) {
            return base.Channel.Endsave(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endsave(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Endsave(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string location = ((string)(inValues[0]));
            System.DateTime holidayDate = ((System.DateTime)(inValues[1]));
            string addedByUser = ((string)(inValues[2]));
            return this.Beginsave(location, holidayDate, addedByUser, callback, asyncState);
        }
        
        private object[] OnEndsave(System.IAsyncResult result) {
            bool retVal = this.Endsave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsaveCompleted(object state) {
            if ((this.saveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.saveCompleted(this, new saveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void saveAsync(string location, System.DateTime holidayDate, string addedByUser) {
            this.saveAsync(location, holidayDate, addedByUser, null);
        }
        
        public void saveAsync(string location, System.DateTime holidayDate, string addedByUser, object userState) {
            if ((this.onBeginsaveDelegate == null)) {
                this.onBeginsaveDelegate = new BeginOperationDelegate(this.OnBeginsave);
            }
            if ((this.onEndsaveDelegate == null)) {
                this.onEndsaveDelegate = new EndOperationDelegate(this.OnEndsave);
            }
            if ((this.onsaveCompletedDelegate == null)) {
                this.onsaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsaveCompleted);
            }
            base.InvokeAsync(this.onBeginsaveDelegate, new object[] {
                        location,
                        holidayDate,
                        addedByUser}, this.onEndsaveDelegate, this.onsaveCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.getAll(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll request) {
            return base.Channel.getAll(request);
        }
        
        public holidayImpl[] getAll() {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll();
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.BegingetAll(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAll(System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAll();
            return ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).BegingetAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.EndgetAll(System.IAsyncResult result) {
            return base.Channel.EndgetAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public holidayImpl[] EndgetAll(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).EndgetAll(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetAll(callback, asyncState);
        }
        
        private object[] OnEndgetAll(System.IAsyncResult result) {
            holidayImpl[] retVal = this.EndgetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllCompleted(object state) {
            if ((this.getAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllCompleted(this, new getAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllAsync() {
            this.getAllAsync(null);
        }
        
        public void getAllAsync(object userState) {
            if ((this.onBegingetAllDelegate == null)) {
                this.onBegingetAllDelegate = new BeginOperationDelegate(this.OnBegingetAll);
            }
            if ((this.onEndgetAllDelegate == null)) {
                this.onEndgetAllDelegate = new EndOperationDelegate(this.OnEndgetAll);
            }
            if ((this.ongetAllCompletedDelegate == null)) {
                this.ongetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllCompleted);
            }
            base.InvokeAsync(this.onBegingetAllDelegate, null, this.onEndgetAllDelegate, this.ongetAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.delete(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string location, System.DateTime holidayDate) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete();
            inValue.location = location;
            inValue.holidayDate = holidayDate;
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Begindelete(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindelete(string location, System.DateTime holidayDate, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.delete();
            inValue.location = location;
            inValue.holidayDate = holidayDate;
            return ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Begindelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Enddelete(System.IAsyncResult result) {
            return base.Channel.Enddelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Enddelete(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Enddelete(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegindelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string location = ((string)(inValues[0]));
            System.DateTime holidayDate = ((System.DateTime)(inValues[1]));
            return this.Begindelete(location, holidayDate, callback, asyncState);
        }
        
        private object[] OnEnddelete(System.IAsyncResult result) {
            bool retVal = this.Enddelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteCompleted(object state) {
            if ((this.deleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteCompleted(this, new deleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteAsync(string location, System.DateTime holidayDate) {
            this.deleteAsync(location, holidayDate, null);
        }
        
        public void deleteAsync(string location, System.DateTime holidayDate, object userState) {
            if ((this.onBegindeleteDelegate == null)) {
                this.onBegindeleteDelegate = new BeginOperationDelegate(this.OnBegindelete);
            }
            if ((this.onEnddeleteDelegate == null)) {
                this.onEnddeleteDelegate = new EndOperationDelegate(this.OnEnddelete);
            }
            if ((this.ondeleteCompletedDelegate == null)) {
                this.ondeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteCompleted);
            }
            base.InvokeAsync(this.onBegindeleteDelegate, new object[] {
                        location,
                        holidayDate}, this.onEnddeleteDelegate, this.ondeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.get(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get request) {
            return base.Channel.get(request);
        }
        
        public holidayImpl[] get(string location) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get();
            inValue.location = location;
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).get(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Beginget(RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginget(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginget(string location, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get inValue = new RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.get();
            inValue.location = location;
            return ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Beginget(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController.Endget(System.IAsyncResult result) {
            return base.Channel.Endget(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public holidayImpl[] Endget(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.getResponse retVal = ((RequestForQuoteServicesModuleLibrary.HolidayMaintenanceService.HolidayController)(this)).Endget(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginget(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string location = ((string)(inValues[0]));
            return this.Beginget(location, callback, asyncState);
        }
        
        private object[] OnEndget(System.IAsyncResult result) {
            holidayImpl[] retVal = this.Endget(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCompleted(object state) {
            if ((this.getCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCompleted(this, new getCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAsync(string location) {
            this.getAsync(location, null);
        }
        
        public void getAsync(string location, object userState) {
            if ((this.onBegingetDelegate == null)) {
                this.onBegingetDelegate = new BeginOperationDelegate(this.OnBeginget);
            }
            if ((this.onEndgetDelegate == null)) {
                this.onEndgetDelegate = new EndOperationDelegate(this.OnEndget);
            }
            if ((this.ongetCompletedDelegate == null)) {
                this.ongetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCompleted);
            }
            base.InvokeAsync(this.onBegingetDelegate, new object[] {
                        location}, this.onEndgetDelegate, this.ongetCompletedDelegate, userState);
        }
    }
}
