//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForQuoteServicesModuleLibrary.SearchCriteriaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://search.rfq.ws.leon.com/", ConfigurationName="SearchCriteriaService.SearchController")]
    public interface SearchController {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacyResponse updatePrivacy(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacy request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAllResponse getAll(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAll request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.saveResponse save(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.save request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.deleteResponse delete(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.delete request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getResponse get(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.get request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePrivacy", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updatePrivacy {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isPrivate;
        
        public updatePrivacy() {
        }
        
        public updatePrivacy(string owner, string key, bool isPrivate) {
            this.owner = owner;
            this.key = key;
            this.isPrivate = isPrivate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updatePrivacyResponse", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updatePrivacyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updatePrivacyResponse() {
        }
        
        public updatePrivacyResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://search.rfq.ws.leon.com/")]
    public partial class searchCriterion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string controlNameField;
        
        private string controlValueField;
        
        private bool isFilterField;
        
        private bool isFilterFieldSpecified;
        
        private bool isPrivateField;
        
        private bool isPrivateFieldSpecified;
        
        private string keyField;
        
        private string ownerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string controlName {
            get {
                return this.controlNameField;
            }
            set {
                this.controlNameField = value;
                this.RaisePropertyChanged("controlName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string controlValue {
            get {
                return this.controlValueField;
            }
            set {
                this.controlValueField = value;
                this.RaisePropertyChanged("controlValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isFilter {
            get {
                return this.isFilterField;
            }
            set {
                this.isFilterField = value;
                this.RaisePropertyChanged("isFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFilterSpecified {
            get {
                return this.isFilterFieldSpecified;
            }
            set {
                this.isFilterFieldSpecified = value;
                this.RaisePropertyChanged("isFilterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isPrivate {
            get {
                return this.isPrivateField;
            }
            set {
                this.isPrivateField = value;
                this.RaisePropertyChanged("isPrivate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isPrivateSpecified {
            get {
                return this.isPrivateFieldSpecified;
            }
            set {
                this.isPrivateFieldSpecified = value;
                this.RaisePropertyChanged("isPrivateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAll {
        
        public getAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public searchCriterion[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(searchCriterion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string controlName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string controlValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isPrivate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isFilter;
        
        public save() {
        }
        
        public save(string owner, string key, string controlName, string controlValue, bool isPrivate, bool isFilter) {
            this.owner = owner;
            this.key = key;
            this.controlName = controlName;
            this.controlValue = controlValue;
            this.isPrivate = isPrivate;
            this.isFilter = isFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveResponse() {
        }
        
        public saveResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public delete() {
        }
        
        public delete(string owner, string key) {
            this.owner = owner;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class get {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string owner;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        public get() {
        }
        
        public get(string owner, string key) {
            this.owner = owner;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResponse", WrapperNamespace="http://search.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://search.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public searchCriterion[] @return;
        
        public getResponse() {
        }
        
        public getResponse(searchCriterion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchControllerChannel : RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchControllerClient : System.ServiceModel.ClientBase<RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController>, RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController {
        
        public SearchControllerClient() {
        }
        
        public SearchControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacyResponse RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController.updatePrivacy(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacy request) {
            return base.Channel.updatePrivacy(request);
        }
        
        public bool updatePrivacy(string owner, string key, bool isPrivate) {
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacy inValue = new RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacy();
            inValue.owner = owner;
            inValue.key = key;
            inValue.isPrivate = isPrivate;
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.updatePrivacyResponse retVal = ((RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController)(this)).updatePrivacy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAllResponse RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController.getAll(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAll request) {
            return base.Channel.getAll(request);
        }
        
        public searchCriterion[] getAll() {
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAll inValue = new RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAll();
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.saveResponse RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController.save(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.save request) {
            return base.Channel.save(request);
        }
        
        public bool save(string owner, string key, string controlName, string controlValue, bool isPrivate, bool isFilter) {
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.save inValue = new RequestForQuoteServicesModuleLibrary.SearchCriteriaService.save();
            inValue.owner = owner;
            inValue.key = key;
            inValue.controlName = controlName;
            inValue.controlValue = controlValue;
            inValue.isPrivate = isPrivate;
            inValue.isFilter = isFilter;
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.deleteResponse RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController.delete(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string owner, string key) {
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.delete inValue = new RequestForQuoteServicesModuleLibrary.SearchCriteriaService.delete();
            inValue.owner = owner;
            inValue.key = key;
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getResponse RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController.get(RequestForQuoteServicesModuleLibrary.SearchCriteriaService.get request) {
            return base.Channel.get(request);
        }
        
        public searchCriterion[] get(string owner, string key) {
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.get inValue = new RequestForQuoteServicesModuleLibrary.SearchCriteriaService.get();
            inValue.owner = owner;
            inValue.key = key;
            RequestForQuoteServicesModuleLibrary.SearchCriteriaService.getResponse retVal = ((RequestForQuoteServicesModuleLibrary.SearchCriteriaService.SearchController)(this)).get(inValue);
            return retVal.@return;
        }
    }
}
