//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RequestForQuoteServicesModuleLibrary.UserMaintenanceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://user.rfq.ws.leon.com/", ConfigurationName="UserMaintenanceService.UserController")]
    public interface UserController {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse updateValidity(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginupdateValidity(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse EndupdateValidity(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse getAll(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetAll(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse EndgetAll(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse delete(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Begindelete(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse Enddelete(System.IAsyncResult result);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse save(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginsave(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save request, System.AsyncCallback callback, object asyncState);
        
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse Endsave(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidity", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidity {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isValid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updatedByUser;
        
        public updateValidity() {
        }
        
        public updateValidity(string userId, bool isValid, string updatedByUser) {
            this.userId = userId;
            this.isValid = isValid;
            this.updatedByUser = updatedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateValidityResponse", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class updateValidityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public updateValidityResponse() {
        }
        
        public updateValidityResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://user.rfq.ws.leon.com/")]
    public partial class userDetailImpl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailAddressField;
        
        private string firstNameField;
        
        private int groupIdField;
        
        private bool isValidField;
        
        private string lastNameField;
        
        private string locationNameField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int groupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
                this.RaisePropertyChanged("groupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAll {
        
        public getAll() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public userDetailImpl[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(userDetailImpl[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        public delete() {
        }
        
        public delete(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class deleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public deleteResponse() {
        }
        
        public deleteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class save {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locationName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int groupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string savedByUser;
        
        public save() {
        }
        
        public save(string userId, string firstName, string lastName, string emailAddress, string locationName, int groupId, string savedByUser) {
            this.userId = userId;
            this.firstName = firstName;
            this.lastName = lastName;
            this.emailAddress = emailAddress;
            this.locationName = locationName;
            this.groupId = groupId;
            this.savedByUser = savedByUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://user.rfq.ws.leon.com/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://user.rfq.ws.leon.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public saveResponse() {
        }
        
        public saveResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserControllerChannel : RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateValidityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateValidityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public userDetailImpl[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((userDetailImpl[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class saveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public saveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserControllerClient : System.ServiceModel.ClientBase<RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController>, RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController {
        
        private BeginOperationDelegate onBeginupdateValidityDelegate;
        
        private EndOperationDelegate onEndupdateValidityDelegate;
        
        private System.Threading.SendOrPostCallback onupdateValidityCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllDelegate;
        
        private EndOperationDelegate onEndgetAllDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteDelegate;
        
        private EndOperationDelegate onEnddeleteDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginsaveDelegate;
        
        private EndOperationDelegate onEndsaveDelegate;
        
        private System.Threading.SendOrPostCallback onsaveCompletedDelegate;
        
        public UserControllerClient() {
        }
        
        public UserControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<updateValidityCompletedEventArgs> updateValidityCompleted;
        
        public event System.EventHandler<getAllCompletedEventArgs> getAllCompleted;
        
        public event System.EventHandler<deleteCompletedEventArgs> deleteCompleted;
        
        public event System.EventHandler<saveCompletedEventArgs> saveCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.updateValidity(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity request) {
            return base.Channel.updateValidity(request);
        }
        
        public bool updateValidity(string userId, bool isValid, string updatedByUser) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity();
            inValue.userId = userId;
            inValue.isValid = isValid;
            inValue.updatedByUser = updatedByUser;
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).updateValidity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.BeginupdateValidity(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateValidity(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateValidity(string userId, bool isValid, string updatedByUser, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidity();
            inValue.userId = userId;
            inValue.isValid = isValid;
            inValue.updatedByUser = updatedByUser;
            return ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).BeginupdateValidity(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.EndupdateValidity(System.IAsyncResult result) {
            return base.Channel.EndupdateValidity(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndupdateValidity(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.updateValidityResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).EndupdateValidity(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginupdateValidity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userId = ((string)(inValues[0]));
            bool isValid = ((bool)(inValues[1]));
            string updatedByUser = ((string)(inValues[2]));
            return this.BeginupdateValidity(userId, isValid, updatedByUser, callback, asyncState);
        }
        
        private object[] OnEndupdateValidity(System.IAsyncResult result) {
            bool retVal = this.EndupdateValidity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateValidityCompleted(object state) {
            if ((this.updateValidityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateValidityCompleted(this, new updateValidityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateValidityAsync(string userId, bool isValid, string updatedByUser) {
            this.updateValidityAsync(userId, isValid, updatedByUser, null);
        }
        
        public void updateValidityAsync(string userId, bool isValid, string updatedByUser, object userState) {
            if ((this.onBeginupdateValidityDelegate == null)) {
                this.onBeginupdateValidityDelegate = new BeginOperationDelegate(this.OnBeginupdateValidity);
            }
            if ((this.onEndupdateValidityDelegate == null)) {
                this.onEndupdateValidityDelegate = new EndOperationDelegate(this.OnEndupdateValidity);
            }
            if ((this.onupdateValidityCompletedDelegate == null)) {
                this.onupdateValidityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateValidityCompleted);
            }
            base.InvokeAsync(this.onBeginupdateValidityDelegate, new object[] {
                        userId,
                        isValid,
                        updatedByUser}, this.onEndupdateValidityDelegate, this.onupdateValidityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.getAll(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll request) {
            return base.Channel.getAll(request);
        }
        
        public userDetailImpl[] getAll() {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll();
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.BegingetAll(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetAll(System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAll();
            return ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).BegingetAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.EndgetAll(System.IAsyncResult result) {
            return base.Channel.EndgetAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public userDetailImpl[] EndgetAll(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.getAllResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).EndgetAll(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetAll(callback, asyncState);
        }
        
        private object[] OnEndgetAll(System.IAsyncResult result) {
            userDetailImpl[] retVal = this.EndgetAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllCompleted(object state) {
            if ((this.getAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllCompleted(this, new getAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllAsync() {
            this.getAllAsync(null);
        }
        
        public void getAllAsync(object userState) {
            if ((this.onBegingetAllDelegate == null)) {
                this.onBegingetAllDelegate = new BeginOperationDelegate(this.OnBegingetAll);
            }
            if ((this.onEndgetAllDelegate == null)) {
                this.onEndgetAllDelegate = new EndOperationDelegate(this.OnEndgetAll);
            }
            if ((this.ongetAllCompletedDelegate == null)) {
                this.ongetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllCompleted);
            }
            base.InvokeAsync(this.onBegingetAllDelegate, null, this.onEndgetAllDelegate, this.ongetAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.delete(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete request) {
            return base.Channel.delete(request);
        }
        
        public bool delete(string userId) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete();
            inValue.userId = userId;
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).delete(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.Begindelete(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begindelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begindelete(string userId, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.delete();
            inValue.userId = userId;
            return ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).Begindelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.Enddelete(System.IAsyncResult result) {
            return base.Channel.Enddelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Enddelete(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.deleteResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).Enddelete(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegindelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userId = ((string)(inValues[0]));
            return this.Begindelete(userId, callback, asyncState);
        }
        
        private object[] OnEnddelete(System.IAsyncResult result) {
            bool retVal = this.Enddelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteCompleted(object state) {
            if ((this.deleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteCompleted(this, new deleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteAsync(string userId) {
            this.deleteAsync(userId, null);
        }
        
        public void deleteAsync(string userId, object userState) {
            if ((this.onBegindeleteDelegate == null)) {
                this.onBegindeleteDelegate = new BeginOperationDelegate(this.OnBegindelete);
            }
            if ((this.onEnddeleteDelegate == null)) {
                this.onEnddeleteDelegate = new EndOperationDelegate(this.OnEnddelete);
            }
            if ((this.ondeleteCompletedDelegate == null)) {
                this.ondeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteCompleted);
            }
            base.InvokeAsync(this.onBegindeleteDelegate, new object[] {
                        userId}, this.onEnddeleteDelegate, this.ondeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.save(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save request) {
            return base.Channel.save(request);
        }
        
        public bool save(string userId, string firstName, string lastName, string emailAddress, string locationName, int groupId, string savedByUser) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save();
            inValue.userId = userId;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.emailAddress = emailAddress;
            inValue.locationName = locationName;
            inValue.groupId = groupId;
            inValue.savedByUser = savedByUser;
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.Beginsave(RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsave(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsave(string userId, string firstName, string lastName, string emailAddress, string locationName, int groupId, string savedByUser, System.AsyncCallback callback, object asyncState) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save inValue = new RequestForQuoteServicesModuleLibrary.UserMaintenanceService.save();
            inValue.userId = userId;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.emailAddress = emailAddress;
            inValue.locationName = locationName;
            inValue.groupId = groupId;
            inValue.savedByUser = savedByUser;
            return ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).Beginsave(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController.Endsave(System.IAsyncResult result) {
            return base.Channel.Endsave(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool Endsave(System.IAsyncResult result) {
            RequestForQuoteServicesModuleLibrary.UserMaintenanceService.saveResponse retVal = ((RequestForQuoteServicesModuleLibrary.UserMaintenanceService.UserController)(this)).Endsave(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginsave(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userId = ((string)(inValues[0]));
            string firstName = ((string)(inValues[1]));
            string lastName = ((string)(inValues[2]));
            string emailAddress = ((string)(inValues[3]));
            string locationName = ((string)(inValues[4]));
            int groupId = ((int)(inValues[5]));
            string savedByUser = ((string)(inValues[6]));
            return this.Beginsave(userId, firstName, lastName, emailAddress, locationName, groupId, savedByUser, callback, asyncState);
        }
        
        private object[] OnEndsave(System.IAsyncResult result) {
            bool retVal = this.Endsave(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsaveCompleted(object state) {
            if ((this.saveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.saveCompleted(this, new saveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void saveAsync(string userId, string firstName, string lastName, string emailAddress, string locationName, int groupId, string savedByUser) {
            this.saveAsync(userId, firstName, lastName, emailAddress, locationName, groupId, savedByUser, null);
        }
        
        public void saveAsync(string userId, string firstName, string lastName, string emailAddress, string locationName, int groupId, string savedByUser, object userState) {
            if ((this.onBeginsaveDelegate == null)) {
                this.onBeginsaveDelegate = new BeginOperationDelegate(this.OnBeginsave);
            }
            if ((this.onEndsaveDelegate == null)) {
                this.onEndsaveDelegate = new EndOperationDelegate(this.OnEndsave);
            }
            if ((this.onsaveCompletedDelegate == null)) {
                this.onsaveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsaveCompleted);
            }
            base.InvokeAsync(this.onBeginsaveDelegate, new object[] {
                        userId,
                        firstName,
                        lastName,
                        emailAddress,
                        locationName,
                        groupId,
                        savedByUser}, this.onEndsaveDelegate, this.onsaveCompletedDelegate, userState);
        }
    }
}
